name: CPP CI

on:
  pull_request:

concurrency:
    # Cancel any CI/CD workflow currently in progress for the same PR.
    # Allow running concurrently with any other commits.
    group: build-${{ github.event.pull_request.number || github.sha }}
    cancel-in-progress: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**.md"]'

  build_ubuntu:
    strategy:
      matrix:
        configurations: [Debug, Release]
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    env:
      # Configuration type to build.  For documentation on how build matrices work, see
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}
          cmake --build build -j $(nproc)

      - name: Run unit tests
        working-directory: ./build/test
        run: ./tests -d yes

      - name: Upload rst2rfcxml binary
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: Ubuntu ${{matrix.configurations}} rst2rfcxml
          path: ${{github.workspace}}/build/rst2rfcxml/rst2rfcxml
          retention-days: 5

      - name: Upload Build Output
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: Ubuntu ${{matrix.configurations}} build
          path: ${{github.workspace}}/build
          retention-days: 5

  build_windows:
    strategy:
      matrix:
        configurations: [Debug, Release]
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: windows-latest
    env:
      # Configuration type to build.  For documentation on how build matrices work, see
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build
          cmake -B build
          cmake --build build -j $(nproc) --config ${{env.BUILD_CONFIGURATION}}

      - name: Run unit tests
        run: ./build/test/${{env.BUILD_CONFIGURATION}}/tests.exe -d yes

      - name: Upload rst2rfcxml binary
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: Windows ${{matrix.configurations}} rst2rfcxml.exe
          path: ${{github.workspace}}/build/rst2rfcxml/${{env.BUILD_CONFIGURATION}}/rst2rfcxml.exe
          retention-days: 5

      - name: Upload Build Output
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: Windows ${{matrix.configurations}} build
          path: ${{github.workspace}}/build
          retention-days: 5
