---
name: CPP CI

on:
  pull_request:

concurrency:
  # Cancel any CI/CD workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_ubuntu:
    strategy:
      matrix:
        configurations: [Debug, Release]
    runs-on: ubuntu-20.04
    env:
      # Configuration type to build.  For documentation on how build matrices work, see
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'false'
          paths_ignore: '["**.md"]'

      - uses: actions/checkout@v4
        if: steps.skip_check.outputs.should_skip != 'true'
        with:
          submodules: 'recursive'

      - name: Build
        if: steps.skip_check.outputs.should_skip != 'true'
        run: |
          mkdir build
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}
          cmake --build build -j $(nproc)

      - name: Run unit tests
        if: steps.skip_check.outputs.should_skip != 'true'
        working-directory: ./build/test
        run: ./tests -d yes

      - name: Upload rst2rfcxml binary
        if: steps.skip_check.outputs.should_skip != 'true'
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: Ubuntu ${{matrix.configurations}} rst2rfcxml
          path: ${{github.workspace}}/build/rst2rfcxml/rst2rfcxml
          retention-days: 5

  build_windows:
    strategy:
      matrix:
        configurations: [Debug, Release]
    runs-on: windows-latest
    env:
      # Configuration type to build.  For documentation on how build matrices work, see
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'false'
          paths_ignore: '["**.md"]'

      - uses: actions/checkout@v4
        if: steps.skip_check.outputs.should_skip != 'true'
        with:
          submodules: 'recursive'

      - name: Build
        if: steps.skip_check.outputs.should_skip != 'true'
        run: |
          mkdir build
          cmake -B build
          cmake --build build -j $(nproc) --config ${{env.BUILD_CONFIGURATION}}

      - name: Run unit tests
        if: steps.skip_check.outputs.should_skip != 'true'
        run: ./build/test/${{env.BUILD_CONFIGURATION}}/tests.exe -d yes

      - name: Upload rst2rfcxml binary
        if: steps.skip_check.outputs.should_skip != 'true'
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: Windows ${{matrix.configurations}} rst2rfcxml.exe
          path: ${{github.workspace}}/build/rst2rfcxml/${{env.BUILD_CONFIGURATION}}/rst2rfcxml.exe
          retention-days: 5

  build_macos:
    strategy:
      matrix:
        configurations: [Debug, Release]
    runs-on: macos-14
    env:
      # Configuration type to build.  For documentation on how build matrices work, see
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'false'
          paths_ignore: '["**.md"]'

      - uses: actions/checkout@v4
        if: steps.skip_check.outputs.should_skip != 'true'
        with:
          submodules: 'recursive'

      - name: Build
        if: steps.skip_check.outputs.should_skip != 'true'
        run: |
          mkdir build
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}
          cmake --build build -j $(nproc)

      - name: Run unit tests
        if: steps.skip_check.outputs.should_skip != 'true'
        working-directory: ./build/test
        run: ./tests -d yes

      - name: Upload rst2rfcxml binary
        if: steps.skip_check.outputs.should_skip != 'true'
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: MacOS ${{matrix.configurations}} rst2rfcxml
          path: ${{github.workspace}}/build/rst2rfcxml/rst2rfcxml
          retention-days: 5
